---
title: "Semi-automating References"
output: html_document
bibliography: BibListReferences.bib
nocite: |
  @WickhamGrolemund2017
  @Kabacoff2015
  @Anscombe1973
  [@Healy2018]
---

A report is written in plain English (Author, 2024) *without using citationkey*, such as `[@author2024]`. 
See below.

This can be found in earlier studies (Anscombe, 1973; Kabacoff, 2015).

Is it possible to just print the references list?
    
Yes, **nocite** creates a Bibliography list. Have a closer look at the end of the converted document! This markdown file will produce three items in the bibliography list at the end. 

Please note that *you still need a bib file*! Ensure to indent under `nocite`. Otherwise, this md file won't compile! 
Note that there is no need to sort the list.
(It'll be easier to keep track if you do, though!).
Unlike in-text citations, square brackets are not required.

To convert to a Word file, use as below.

You can use the full path for the bib file.

```
---
title: "References"
output: word_document
bibliography: W:/path/Zotero/references.bib
nocite: |
  @WickhamGrolemund2017
  @Anscombe1973
  @Kabacoff2015
  @Healy2018
---
```

Need to use your own docx Ref template?
Must change the ref system style? See below.

```
---
title: "References"
output:
  word_document:
    reference_docx: Bib_Template.docx
bibliography: W:/path/Zotero/references.bib
csl: W:/path/Zotero/styles/apa.csl
nocite: |
  @WickhamGrolemund2017
  @Anscombe1973
  @Kabacoff2015
  @Healy2018
---
```

Hardcore semiautomation individuals can consider `includetext` field in Word. It has its own caveat, though!

# References
