---
title: "Custom fonts with xelatex"
author: ""
date: "October 2024"
urlcolor: orange
mainfont: Times New Roman
output: 
  pdf_document: 
    latex_engine: xelatex
    number_sections: true
---

Can we format fonts for the entire document?

# Specify YAML
We need to specify xelatex as latex_engine.

## Option 1
Set the font, and specify xelatex as latex_engine.

```
mainfont: Times New Roman
output: 
  pdf_document: 
    latex_engine: xelatex
```

## Option 2
Does the option 1 not work? Add another line to specify fontspec package and use the format as shown below.

```
header-includes:
  - \usepackage{fontspec}
  - \setmainfont{Times New Roman}
output: 
  pdf_document: 
    latex_engine: xelatex
```


# Tested fonts
Times New Roman, Calibri Light, Tahoma,
Palatino Linotype, Source Sans Pro (does not work with SourceSansPro and sourcesanspro),  Open Sans, Lato


# Troubleshoot

## Won't compile
It is important to place the output argument at the end of YAML if this is the **first time** you are attempting to test a particular font for a resulting PDF file.

```         
output: 
  pdf_document: 
    latex_engine: xelatex
```

By doing so, *tinytex* in RStudio will attempt to install any additional LaTeX packages needed for a particular Rmarkdown file before compiling as a PDF document.

Once this is successful, you may move the `output:` arguments before the `header-includes:` arguments. This is to make the resulting document immediately apparent.

## Font not printed as intended

Check the YAML settings for any mistakes or typo. Due to the typo, the following will not work, and set the font as default.
```
  - \setmainfont: {Calibri Light}
```

## Another approach using fontenc
This involves more complexity; if you test with other fonts, you'll notice that it seems not so straightforward! Hence, using the fontspec package is recommended.

```         
header-includes:
   - \usepackage[default]{sourcesanspro}
   - \usepackage[T1]{fontenc}
mainfont: sourcesanspro
output: pdf_document
```
Note that with fontenc package, there is no need to set a *latex_engine*, as the RStudio's (Sweave) default, *pdfLaTeX* is used.

See details here [Cecina Babich Morrow's page] <https://babichmorrowc.github.io/post/changing-fonts-in-rmarkdown-pdfs/>

For a discussion on `fontenc` and the usage of pdfLaTex, see [A discussion on fontenc],\
    <https://tex.stackexchange.com/questions/664/why-should-i-use-usepackaget1fontenc>
    
## Other errors  
Remove emoticons.

